<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BookSeederPart1 extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'title' => 'Al Quran',
                'author' => 'Tidak Diketahui',
                'publisher' => 'Tidak Diketahui',
                'publish_year' => 0000,
                'category_id' => 1,
                'stock' => 17,
                'location' => 'A1',
            ],
            [
                'id' => 2,
                'title' => 'Pendidikan Agama Islam dan Budi Pekerti',
                'author' => 'Muhammad Ahsan, Sumiyati, dan Mustahdi',
                'publisher' => 'Pusat Kurikulum dan Perbukuan, Balitbang, Kemendikbud',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 10,
                'location' => 'A1',
            ],
            [
                'id' => 3,
                'title' => 'Personality Plus',
                'author' => 'Florence Littauer',
                'publisher' => 'KARISMA Publishing Group',
                'publish_year' => 2011,
                'category_id' => 2,
                'stock' => 1,
                'location' => 'A2',
            ],
            [
                'id' => 4,
                'title' => 'Hidup dan Amarah',
                'author' => 'Thubten Chodrom',
                'publisher' => 'Dian Dharma',
                'publish_year' => 2003,
                'category_id' => 3,
                'stock' => 1,
                'location' => 'A2',
            ],
            [
                'id' => 5,
                'title' => 'Bakat dan Kemampuan',
                'author' => 'Drs Bambang Marhijianto',
                'publisher' => 'CV. Bintang Pelajar',
                'publish_year' => 1990,
                'category_id' => 4,
                'stock' => 1,
                'location' => 'A2',
            ],
                        [
                'id' => 6,
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'publish_year' => 2005,
                'category_id' => 3,
                'stock' => 3,
                'location' => 'B1',
            ],
            [
                'id' => 7,
                'title' => 'Sang Pemimpi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'publish_year' => 2006,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'B1',
            ],
            [
                'id' => 8,
                'title' => 'Edensor',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'publish_year' => 2007,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'B1',
            ],
            [
                'id' => 9,
                'title' => 'Maryamah Karpov',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'publish_year' => 2008,
                'category_id' => 3,
                'stock' => 1,
                'location' => 'B1',
            ],
            [
                'id' => 10,
                'title' => 'Negeri 5 Menara',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2009,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'B2',
            ],
            [
                'id' => 11,
                'title' => 'Ranah 3 Warna',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2011,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'B2',
            ],
            [
                'id' => 12,
                'title' => 'Rantau 1 Muara',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2013,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'B2',
            ],
            [
                'id' => 13,
                'title' => 'Bumi',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2014,
                'category_id' => 32,
                'stock' => 5,
                'location' => 'C1',
            ],
            [
                'id' => 14,
                'title' => 'Bulan',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2015,
                'category_id' => 32,
                'stock' => 5,
                'location' => 'C1',
            ],
            [
                'id' => 15,
                'title' => 'Matahari',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2016,
                'category_id' => 32,
                'stock' => 5,
                'location' => 'C1',
            ],
            [
                'id' => 16,
                'title' => 'Bintang',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2017,
                'category_id' => 32,
                'stock' => 4,
                'location' => 'C1',
            ],
            [
                'id' => 17,
                'title' => 'Komet',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2018,
                'category_id' => 32,
                'stock' => 3,
                'location' => 'C1',
            ],
            [
                'id' => 18,
                'title' => 'Komet Minor',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2019,
                'category_id' => 32,
                'stock' => 3,
                'location' => 'C1',
            ],
            [
                'id' => 19,
                'title' => 'Selena',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2020,
                'category_id' => 32,
                'stock' => 4,
                'location' => 'C2',
            ],
            [
                'id' => 20,
                'title' => 'Nebula',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2020,
                'category_id' => 32,
                'stock' => 4,
                'location' => 'C2',
            ],
            [
                'id' => 21,
                'title' => 'Si Anak Badai',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2018,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C2',
            ],
            [
                'id' => 22,
                'title' => 'Si Anak Spesial',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2019,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C2',
            ],
            [
                'id' => 23,
                'title' => 'Si Anak Pintar',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2020,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C2',
            ],
            [
                'id' => 24,
                'title' => 'Hafalan Shalat Delisa',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'publish_year' => 2005,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 25,
                'title' => 'Moga Bunda Disayang Allah',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'publish_year' => 2006,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 26,
                'title' => 'Daun yang Jatuh Tak Pernah Membenci Angin',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2010,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 27,
                'title' => 'Rindu',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'publish_year' => 2014,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 28,
                'title' => 'Pulang',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'publish_year' => 2015,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 29,
                'title' => 'Pergi',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'publish_year' => 2018,
                'category_id' => 3,
                'stock' => 2,
                'location' => 'C3',
            ],
            [
                'id' => 30,
                'title' => 'Bumi Manusia',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1980,
                'category_id' => 28,
                'stock' => 2,
                'location' => 'D1',
            ],
            [
                'id' => 31,
                'title' => 'Anak Semua Bangsa',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1981,
                'category_id' => 28,
                'stock' => 2,
                'location' => 'D1',
            ],
            [
                'id' => 32,
                'title' => 'Jejak Langkah',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1985,
                'category_id' => 28,
                'stock' => 2,
                'location' => 'D1',
            ],
            [
                'id' => 33,
                'title' => 'Rumah Kaca',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1988,
                'category_id' => 28,
                'stock' => 2,
                'location' => 'D1',
            ],
            [
                'id' => 34,
                'title' => 'Gadis Pantai',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1962,
                'category_id' => 28,
                'stock' => 1,
                'location' => 'D1',
            ],
            [
                'id' => 35,
                'title' => 'Cerita dari Blora',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1952,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 36,
                'title' => 'Cerita dari Jakarta',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1957,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 37,
                'title' => 'Cerita dari Surabaya',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1958,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 38,
                'title' => 'Cerita dari Yogyakarta',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1960,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 39,
                'title' => 'Cerita dari Bali',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1961,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 40,
                'title' => 'Cerita dari Kalimantan',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1963,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 41,
                'title' => 'Cerita dari Sumatra',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'publish_year' => 1965,
                'category_id' => 25,
                'stock' => 1,
                'location' => 'D2',
            ],
            [
                'id' => 42,
                'title' => 'Ensiklopedia Sejarah Dunia',
                'author' => 'Hugh Chisholm',
                'publisher' => 'Cambridge University Press',
                'publish_year' => 1910,
                'category_id' => 5,
                'stock' => 2,
                'location' => 'E1',
            ],
            [
                'id' => 43,
                'title' => 'Ensiklopedia Indonesia',
                'author' => 'Hasan Shadily',
                'publisher' => 'Ichtiar Baru Van Hoeve',
                'publish_year' => 1980,
                'category_id' => 5,
                'stock' => 2,
                'location' => 'E1',
            ],
            [
                'id' => 44,
                'title' => 'Ensiklopedia Nasional Indonesia',
                'author' => 'Departemen Pendidikan dan Kebudayaan',
                'publisher' => 'PT Cipta Adi Pustaka',
                'publish_year' => 1989,
                'category_id' => 5,
                'stock' => 2,
                'location' => 'E1',
            ],
            [
                'id' => 45,
                'title' => 'Ensiklopedia Sains',
                'author' => 'World Book, Inc.',
                'publisher' => 'World Book, Inc.',
                'publish_year' => 1995,
                'category_id' => 5,
                'stock' => 2,
                'location' => 'E1',
            ],
            [
                'id' => 46,
                'title' => 'Ensiklopedia Biografi Tokoh Dunia',
                'author' => 'John Cannon',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2000,
                'category_id' => 6,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 47,
                'title' => 'Ensiklopedia Islam',
                'author' => 'Departemen Agama RI',
                'publisher' => 'Departemen Agama RI',
                'publish_year' => 2002,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 48,
                'title' => 'Ensiklopedia Pendidikan',
                'author' => 'Departemen Pendidikan Nasional',
                'publisher' => 'Departemen Pendidikan Nasional',
                'publish_year' => 2003,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 49,
                'title' => 'Ensiklopedia Teknologi',
                'author' => 'Departemen Riset dan Teknologi',
                'publisher' => 'Departemen Riset dan Teknologi',
                'publish_year' => 2004,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 50,
                'title' => 'Ensiklopedia Kesehatan',
                'author' => 'Departemen Kesehatan RI',
                'publisher' => 'Departemen Kesehatan RI',
                'publish_year' => 2005,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
                        [
                'id' => 51,
                'title' => 'Ensiklopedia Seni dan Budaya',
                'author' => 'Departemen Kebudayaan dan Pariwisata',
                'publisher' => 'Departemen Kebudayaan dan Pariwisata',
                'publish_year' => 2006,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 52,
                'title' => 'Ensiklopedia Geografi',
                'author' => 'National Geographic Society',
                'publisher' => 'National Geographic Society',
                'publish_year' => 2007,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 53,
                'title' => 'Ensiklopedia Matematika',
                'author' => 'James Tanton',
                'publisher' => 'Facts on File',
                'publish_year' => 2008,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 54,
                'title' => 'Ensiklopedia Fisika',
                'author' => 'Paul G. Hewitt',
                'publisher' => 'Addison-Wesley',
                'publish_year' => 2009,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 55,
                'title' => 'Ensiklopedia Kimia',
                'author' => 'Rayner-Canham',
                'publisher' => 'W. H. Freeman',
                'publish_year' => 2010,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 56,
                'title' => 'Ensiklopedia Biologi',
                'author' => 'Neil A. Campbell',
                'publisher' => 'Pearson',
                'publish_year' => 2011,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 57,
                'title' => 'Ensiklopedia Komputer',
                'author' => 'Andrew S. Tanenbaum',
                'publisher' => 'Prentice Hall',
                'publish_year' => 2012,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 58,
                'title' => 'Ensiklopedia Psikologi',
                'author' => 'Raymond J. Corsini',
                'publisher' => 'Wiley',
                'publish_year' => 2013,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 59,
                'title' => 'Ensiklopedia Ekonomi',
                'author' => 'David R. Henderson',
                'publisher' => 'Palgrave Macmillan',
                'publish_year' => 2014,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 60,
                'title' => 'Ensiklopedia Politik',
                'author' => 'George Thomas Kurian',
                'publisher' => 'CQ Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 61,
                'title' => 'Ensiklopedia Hukum',
                'author' => 'W. J. Stewart',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 62,
                'title' => 'Ensiklopedia Militer',
                'author' => 'Trevor N. Dupuy',
                'publisher' => 'Harper & Row',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 63,
                'title' => 'Ensiklopedia Astronomi',
                'author' => 'Patrick Moore',
                'publisher' => 'Springer',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 64,
                'title' => 'Ensiklopedia Musik',
                'author' => 'Stanley Sadie',
                'publisher' => 'Macmillan',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 65,
                'title' => 'Ensiklopedia Sastra',
                'author' => 'Eric Partridge',
                'publisher' => 'Routledge',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 66,
                'title' => 'Ensiklopedia Antropologi',
                'author' => 'David Levinson',
                'publisher' => 'Sage Publications',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 67,
                'title' => 'Ensiklopedia Arkeologi',
                'author' => 'Tim Murray',
                'publisher' => 'ABC-CLIO',
                'publish_year' => 2001,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 68,
                'title' => 'Ensiklopedia Pertanian',
                'author' => 'Charles W. Bamforth',
                'publisher' => 'Springer',
                'publish_year' => 2002,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 69,
                'title' => 'Ensiklopedia Perikanan',
                'author' => 'Emilio F. Moran',
                'publisher' => 'Wiley-Blackwell',
                'publish_year' => 2003,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 70,
                'title' => 'Ensiklopedia Peternakan',
                'author' => 'Wilson G. Pond',
                'publisher' => 'Springer',
                'publish_year' => 2004,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 71,
                'title' => 'Ensiklopedia Kehutanan',
                'author' => 'John A. Matthews',
                'publisher' => 'Springer',
                'publish_year' => 2005,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 72,
                'title' => 'Ensiklopedia Energi',
                'author' => 'Cutler J. Cleveland',
                'publisher' => 'Elsevier',
                'publish_year' => 2006,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 73,
                'title' => 'Ensiklopedia Teknologi Informasi',
                'author' => 'Phillip A. Laplante',
                'publisher' => 'CRC Press',
                'publish_year' => 2007,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 74,
                'title' => 'Ensiklopedia Robotika',
                'author' => 'Bruno Siciliano',
                'publisher' => 'Springer',
                'publish_year' => 2008,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 75,
                'title' => 'Ensiklopedia Kecerdasan Buatan',
                'author' => 'Stuart Russell',
                'publisher' => 'Cambridge University Press',
                'publish_year' => 2009,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 76,
                'title' => 'Ensiklopedia Bahasa dan Linguistik',
                'author' => 'R. E. Asher',
                'publisher' => 'Pergamon',
                'publish_year' => 2010,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 77,
                'title' => 'Ensiklopedia Filsafat',
                'author' => 'Edward Craig',
                'publisher' => 'Routledge',
                'publish_year' => 2011,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 78,
                'title' => 'Ensiklopedia Agama',
                'author' => 'Mircea Eliade',
                'publisher' => 'Macmillan',
                'publish_year' => 2012,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 79,
                'title' => 'Ensiklopedia Mitologi',
                'author' => 'Arthur Cotterell',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2013,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 80,
                'title' => 'Ensiklopedia Seni Rupa',
                'author' => 'John Fleming',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2014,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 81,
                'title' => 'Ensiklopedia Fotografi',
                'author' => 'Michael Freeman',
                'publisher' => 'Thames & Hudson',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 82,
                'title' => 'Ensiklopedia Film',
                'author' => 'Ephraim Katz',
                'publisher' => 'Collins',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 83,
                'title' => 'Ensiklopedia Teater',
                'author' => 'Phyllis Hartnoll',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 84,
                'title' => 'Ensiklopedia Olahraga',
                'author' => 'Frank W. Menke',
                'publisher' => 'A.S. Barnes',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 85,
                'title' => 'Ensiklopedia Sejarah Islam',
                'author' => 'Cyril Glasse',
                'publisher' => 'Rowman & Littlefield',
                'publish_year' => 2019,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 86,
                'title' => 'Ensiklopedia Dunia Islam',
                'author' => 'John L. Esposito',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2020,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 87,
                'title' => 'Ensiklopedia Peradaban Islam',
                'author' => 'Marshall G. S. Hodgson',
                'publisher' => 'University of Chicago Press',
                'publish_year' => 2021,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 88,
                'title' => 'Ensiklopedia Tokoh Muslim Dunia',
                'author' => 'Ali Masudi',
                'publisher' => 'Republika',
                'publish_year' => 2017,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 89,
                'title' => 'Ensiklopedia Tasawuf',
                'author' => 'Seyyed Hossein Nasr',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2018,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 90,
                'title' => 'Ensiklopedia Hadis',
                'author' => 'M. M. Azami',
                'publisher' => 'Islamic Book Trust',
                'publish_year' => 2019,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 91,
                'title' => 'Ensiklopedia Al-Quran',
                'author' => 'Muhammad Fuad Abdul Baqi',
                'publisher' => 'Darus Salam',
                'publish_year' => 2020,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 92,
                'title' => 'Ensiklopedia Sahabat Nabi',
                'author' => 'Ibn Hajar Al-Asqalani',
                'publisher' => 'Dar Al-Fikr',
                'publish_year' => 2015,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 93,
                'title' => 'Ensiklopedia Sirah Nabi',
                'author' => 'Ibn Katsir',
                'publisher' => 'Darus Salam',
                'publish_year' => 2016,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 94,
                'title' => 'Ensiklopedia Fiqih',
                'author' => 'Wahbah Zuhaili',
                'publisher' => 'Dar Al-Fikr',
                'publish_year' => 2017,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 95,
                'title' => 'Ensiklopedia Hadis Shahih',
                'author' => 'Imam Bukhari',
                'publisher' => 'Darus Salam',
                'publish_year' => 2018,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 96,
                'title' => 'Ensiklopedia Tafsir',
                'author' => 'Imam Jalaluddin As-Suyuthi',
                'publisher' => 'Dar Al-Ma\'rifah',
                'publish_year' => 2019,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 97,
                'title' => 'Ensiklopedia Doa dan Dzikir',
                'author' => 'Syaikh Abdul Aziz bin Baz',
                'publisher' => 'Darus Salam',
                'publish_year' => 2020,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 98,
                'title' => 'Ensiklopedia Aqidah',
                'author' => 'Muhammad bin Jamil Zainu',
                'publisher' => 'Darus Salam',
                'publish_year' => 2021,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 99,
                'title' => 'Ensiklopedia Ulama Nusantara',
                'author' => 'KH. Said Aqil Siradj',
                'publisher' => 'PBNU',
                'publish_year' => 2015,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 100,
                'title' => 'Ensiklopedia Tokoh Islam Indonesia',
                'author' => 'Azyumardi Azra',
                'publisher' => 'Gramedia Pustaka Utama',
                'publish_year' => 2016,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E2',
            ],
            [
                'id' => 101,
                'title' => 'Ensiklopedia Pemikiran Islam',
                'author' => 'Harun Nasution',
                'publisher' => 'UI Press',
                'publish_year' => 2017,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 102,
                'title' => 'Ensiklopedia Pendidikan Islam',
                'author' => 'Abuddin Nata',
                'publisher' => 'Rajagrafindo Persada',
                'publish_year' => 2018,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 103,
                'title' => 'Ensiklopedia Perkembangan Islam Modern',
                'author' => 'Fazlur Rahman',
                'publisher' => 'University of Chicago Press',
                'publish_year' => 2019,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 104,
                'title' => 'Ensiklopedia Tokoh Pembaharu Islam',
                'author' => 'Nurcholish Madjid',
                'publisher' => 'Paramadina',
                'publish_year' => 2020,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 105,
                'title' => 'Ensiklopedia Perempuan dalam Islam',
                'author' => 'Fatima Mernissi',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2021,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 106,
                'title' => 'Ensiklopedia Pemikiran Ulama',
                'author' => 'KH. Hasyim Asy\'ari',
                'publisher' => 'PBNU',
                'publish_year' => 2015,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 107,
                'title' => 'Ensiklopedia Tradisi Islam',
                'author' => 'Clifford Geertz',
                'publisher' => 'University of Chicago Press',
                'publish_year' => 2016,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 108,
                'title' => 'Ensiklopedia Kebudayaan Islam',
                'author' => 'Hitti, Philip K.',
                'publisher' => 'Macmillan',
                'publish_year' => 2017,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 109,
                'title' => 'Ensiklopedia Tokoh Besar Islam',
                'author' => 'Ali Shariati',
                'publisher' => 'Syiah Press',
                'publish_year' => 2018,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 110,
                'title' => 'Ensiklopedia Pemikiran Politik Islam',
                'author' => 'John L. Esposito',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2019,
                'category_id' => 1,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 111,
                'title' => 'Ensiklopedia Dunia Modern',
                'author' => 'Various',
                'publisher' => 'Cambridge University Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 112,
                'title' => 'Ensiklopedia Ilmu Alam',
                'author' => 'David Attenborough',
                'publisher' => 'BBC Books',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 113,
                'title' => 'Ensiklopedia Sejarah Dunia',
                'author' => 'Peter N. Stearns',
                'publisher' => 'Houghton Mifflin',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 114,
                'title' => 'Ensiklopedia Politik Dunia',
                'author' => 'Andrew Heywood',
                'publisher' => 'Palgrave Macmillan',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 115,
                'title' => 'Ensiklopedia Sains Modern',
                'author' => 'Stephen Hawking',
                'publisher' => 'Bantam Books',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 116,
                'title' => 'Ensiklopedia Teknologi Masa Kini',
                'author' => 'Ray Kurzweil',
                'publisher' => 'Penguin',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 117,
                'title' => 'Ensiklopedia Ekonomi Global',
                'author' => 'Joseph Stiglitz',
                'publisher' => 'Norton',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 118,
                'title' => 'Ensiklopedia Sosial Budaya',
                'author' => 'Anthony Giddens',
                'publisher' => 'Polity Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 119,
                'title' => 'Ensiklopedia Ilmu Politik',
                'author' => 'Norberto Bobbio',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 120,
                'title' => 'Ensiklopedia Teknologi Digital',
                'author' => 'Nicholas Negroponte',
                'publisher' => 'MIT Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
                        [
                'id' => 121,
                'title' => 'Ensiklopedia Sains dan Teknologi',
                'author' => 'Isaac Asimov',
                'publisher' => 'Doubleday',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 122,
                'title' => 'Ensiklopedia Lingkungan Hidup',
                'author' => 'Vaclav Smil',
                'publisher' => 'MIT Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 123,
                'title' => 'Ensiklopedia Kesehatan',
                'author' => 'C. Everett Koop',
                'publisher' => 'Random House',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 124,
                'title' => 'Ensiklopedia Psikologi Modern',
                'author' => 'Sigmund Freud',
                'publisher' => 'Vintage',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 125,
                'title' => 'Ensiklopedia Fisika Modern',
                'author' => 'Richard Feynman',
                'publisher' => 'Addison-Wesley',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 126,
                'title' => 'Ensiklopedia Matematika Modern',
                'author' => 'Terence Tao',
                'publisher' => 'Springer',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 127,
                'title' => 'Ensiklopedia Bioteknologi',
                'author' => 'Craig Venter',
                'publisher' => 'HarperCollins',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 128,
                'title' => 'Ensiklopedia Kedokteran',
                'author' => 'William Osler',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 129,
                'title' => 'Ensiklopedia Teknologi Kedokteran',
                'author' => 'Eric Topol',
                'publisher' => 'Basic Books',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 130,
                'title' => 'Ensiklopedia Sejarah Ilmu',
                'author' => 'George Sarton',
                'publisher' => 'Harvard University Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 131,
                'title' => 'Ensiklopedia Kebudayaan Dunia',
                'author' => 'UNESCO',
                'publisher' => 'UNESCO Publishing',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 132,
                'title' => 'Ensiklopedia Agama Dunia',
                'author' => 'Huston Smith',
                'publisher' => 'HarperOne',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 133,
                'title' => 'Ensiklopedia Seni Musik',
                'author' => 'Alan P. Merriam',
                'publisher' => 'University of Chicago Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 134,
                'title' => 'Ensiklopedia Seni Pertunjukan',
                'author' => 'Richard Schechner',
                'publisher' => 'Routledge',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 135,
                'title' => 'Ensiklopedia Seni Rupa Modern',
                'author' => 'Herbert Read',
                'publisher' => 'Thames & Hudson',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 136,
                'title' => 'Ensiklopedia Fotografi Modern',
                'author' => 'Susan Sontag',
                'publisher' => 'Farrar, Straus and Giroux',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 137,
                'title' => 'Ensiklopedia Film Dunia',
                'author' => 'David Bordwell',
                'publisher' => 'McGraw-Hill',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 138,
                'title' => 'Ensiklopedia Teater Modern',
                'author' => 'Peter Brook',
                'publisher' => 'Methuen',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 139,
                'title' => 'Ensiklopedia Olahraga Modern',
                'author' => 'David Wallechinsky',
                'publisher' => 'Aurora',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 140,
                'title' => 'Ensiklopedia Tokoh Dunia',
                'author' => 'TIME Magazine Editors',
                'publisher' => 'Time Inc.',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 141,
                'title' => 'Ensiklopedia Ilmuwan Dunia',
                'author' => 'Carl Sagan',
                'publisher' => 'Random House',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 142,
                'title' => 'Ensiklopedia Penemuan',
                'author' => 'James Burke',
                'publisher' => 'Macmillan',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 143,
                'title' => 'Ensiklopedia Transportasi',
                'author' => 'George Bibel',
                'publisher' => 'Johns Hopkins University Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 144,
                'title' => 'Ensiklopedia Energi Terbarukan',
                'author' => 'Daniel Yergin',
                'publisher' => 'Penguin',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 145,
                'title' => 'Ensiklopedia Teknologi Komunikasi',
                'author' => 'Marshall McLuhan',
                'publisher' => 'Routledge',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 146,
                'title' => 'Ensiklopedia Teknologi Internet',
                'author' => 'Tim Berners-Lee',
                'publisher' => 'MIT Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 147,
                'title' => 'Ensiklopedia Teknologi Mobile',
                'author' => 'Steve Jobs',
                'publisher' => 'Apple Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 148,
                'title' => 'Ensiklopedia Teknologi AI',
                'author' => 'Geoffrey Hinton',
                'publisher' => 'MIT Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 149,
                'title' => 'Ensiklopedia Teknologi Blockchain',
                'author' => 'Satoshi Nakamoto',
                'publisher' => 'Crypto Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
            [
                'id' => 150,
                'title' => 'Ensiklopedia Teknologi Cloud',
                'author' => 'Marc Andreessen',
                'publisher' => 'Cloud Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E3',
            ],
                        [
                'id' => 151,
                'title' => 'Ensiklopedia Teknologi Big Data',
                'author' => 'Viktor Mayer-Schönberger',
                'publisher' => 'John Wiley & Sons',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 152,
                'title' => 'Ensiklopedia Teknologi Cybersecurity',
                'author' => 'Bruce Schneier',
                'publisher' => 'Wiley',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 153,
                'title' => 'Ensiklopedia Teknologi Robotika',
                'author' => 'Hans Moravec',
                'publisher' => 'Oxford University Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 154,
                'title' => 'Ensiklopedia Teknologi Otomotif',
                'author' => 'Carroll Shelby',
                'publisher' => 'Automotive Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 155,
                'title' => 'Ensiklopedia Teknologi Penerbangan',
                'author' => 'Howard Hughes',
                'publisher' => 'Aviation Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 156,
                'title' => 'Ensiklopedia Teknologi Antariksa',
                'author' => 'Elon Musk',
                'publisher' => 'SpaceX Publishing',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 157,
                'title' => 'Ensiklopedia Teknologi Militer',
                'author' => 'Norman Friedman',
                'publisher' => 'Naval Institute Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 158,
                'title' => 'Ensiklopedia Teknologi Nuklir',
                'author' => 'Richard Rhodes',
                'publisher' => 'Simon & Schuster',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 159,
                'title' => 'Ensiklopedia Teknologi Energi',
                'author' => 'Amory Lovins',
                'publisher' => 'Rocky Mountain Institute',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 160,
                'title' => 'Ensiklopedia Teknologi Pertanian',
                'author' => 'Norman Borlaug',
                'publisher' => 'Agriculture Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 161,
                'title' => 'Ensiklopedia Teknologi Pangan',
                'author' => 'Harold McGee',
                'publisher' => 'Scribner',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 162,
                'title' => 'Ensiklopedia Teknologi Farmasi',
                'author' => 'Paul L. Munson',
                'publisher' => 'Elsevier',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 163,
                'title' => 'Ensiklopedia Teknologi Biologi',
                'author' => 'James Watson',
                'publisher' => 'Cold Spring Harbor Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 164,
                'title' => 'Ensiklopedia Teknologi Kimia',
                'author' => 'Linus Pauling',
                'publisher' => 'McGraw-Hill',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 165,
                'title' => 'Ensiklopedia Teknologi Fisika',
                'author' => 'Albert Einstein',
                'publisher' => 'Springer',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 166,
                'title' => 'Ensiklopedia Teknologi Matematika',
                'author' => 'John Nash',
                'publisher' => 'Princeton University Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 167,
                'title' => 'Ensiklopedia Teknologi Komputer',
                'author' => 'Alan Turing',
                'publisher' => 'Cambridge University Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 168,
                'title' => 'Ensiklopedia Teknologi Elektronika',
                'author' => 'Nikola Tesla',
                'publisher' => 'Routledge',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 169,
                'title' => 'Ensiklopedia Teknologi Telekomunikasi',
                'author' => 'Claude Shannon',
                'publisher' => 'Bell Labs Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 170,
                'title' => 'Ensiklopedia Teknologi Jaringan',
                'author' => 'Vint Cerf',
                'publisher' => 'MIT Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 171,
                'title' => 'Ensiklopedia Teknologi Multimedia',
                'author' => 'Douglas Engelbart',
                'publisher' => 'ACM Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 172,
                'title' => 'Ensiklopedia Teknologi Virtual Reality',
                'author' => 'Jaron Lanier',
                'publisher' => 'MIT Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 173,
                'title' => 'Ensiklopedia Teknologi Augmented Reality',
                'author' => 'Mark Zuckerberg',
                'publisher' => 'Meta Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 174,
                'title' => 'Ensiklopedia Teknologi Game',
                'author' => 'Shigeru Miyamoto',
                'publisher' => 'Nintendo Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 175,
                'title' => 'Ensiklopedia Teknologi Grafis',
                'author' => 'John Carmack',
                'publisher' => 'Graphics Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],

                        [
                'id' => 176,
                'title' => 'Ensiklopedia Teknologi Animasi',
                'author' => 'Hayao Miyazaki',
                'publisher' => 'Studio Ghibli Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 177,
                'title' => 'Ensiklopedia Teknologi Desain',
                'author' => 'Dieter Rams',
                'publisher' => 'Design Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E4',
            ],
            [
                'id' => 178,
                'title' => 'Ensiklopedia Teknologi Arsitektur',
                'author' => 'Frank Lloyd Wright',
                'publisher' => 'Architecture Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 179,
                'title' => 'Ensiklopedia Teknologi Sipil',
                'author' => 'Gustave Eiffel',
                'publisher' => 'Civil Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 180,
                'title' => 'Ensiklopedia Teknologi Kelautan',
                'author' => 'Jacques Cousteau',
                'publisher' => 'Marine Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 181,
                'title' => 'Ensiklopedia Teknologi Geologi',
                'author' => 'Charles Lyell',
                'publisher' => 'Geology Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 182,
                'title' => 'Ensiklopedia Teknologi Meteorologi',
                'author' => 'Alfred Wegener',
                'publisher' => 'Climate Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 183,
                'title' => 'Ensiklopedia Teknologi Astronomi',
                'author' => 'Galileo Galilei',
                'publisher' => 'Astronomy Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 184,
                'title' => 'Ensiklopedia Teknologi Kehutanan',
                'author' => 'Gifford Pinchot',
                'publisher' => 'Forestry Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 185,
                'title' => 'Ensiklopedia Teknologi Lingkungan',
                'author' => 'Rachel Carson',
                'publisher' => 'Environment Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 186,
                'title' => 'Ensiklopedia Teknologi Sosial',
                'author' => 'Manuel Castells',
                'publisher' => 'Sociology Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 187,
                'title' => 'Ensiklopedia Teknologi Ekonomi',
                'author' => 'John Maynard Keynes',
                'publisher' => 'Economy Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 188,
                'title' => 'Ensiklopedia Teknologi Politik',
                'author' => 'Niccolò Machiavelli',
                'publisher' => 'Political Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 189,
                'title' => 'Ensiklopedia Teknologi Hukum',
                'author' => 'Hans Kelsen',
                'publisher' => 'Law Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 190,
                'title' => 'Ensiklopedia Teknologi Pendidikan',
                'author' => 'John Dewey',
                'publisher' => 'Education Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 191,
                'title' => 'Ensiklopedia Teknologi Bahasa',
                'author' => 'Noam Chomsky',
                'publisher' => 'Linguistic Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 192,
                'title' => 'Ensiklopedia Teknologi Sastra',
                'author' => 'T.S. Eliot',
                'publisher' => 'Literature Press',
                'publish_year' => 2015,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 193,
                'title' => 'Ensiklopedia Teknologi Budaya',
                'author' => 'Clifford Geertz',
                'publisher' => 'Culture Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 194,
                'title' => 'Ensiklopedia Teknologi Antropologi',
                'author' => 'Bronisław Malinowski',
                'publisher' => 'Anthropology Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 195,
                'title' => 'Ensiklopedia Teknologi Filsafat',
                'author' => 'Aristoteles',
                'publisher' => 'Philosophy Press',
                'publish_year' => 2018,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 196,
                'title' => 'Ensiklopedia Teknologi Etika',
                'author' => 'Immanuel Kant',
                'publisher' => 'Ethics Press',
                'publish_year' => 2019,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 197,
                'title' => 'Ensiklopedia Teknologi Psikologi',
                'author' => 'Carl Gustav Jung',
                'publisher' => 'Psychology Press',
                'publish_year' => 2020,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 198,
                'title' => 'Ensiklopedia Teknologi Sejarah',
                'author' => 'Herodotus',
                'publisher' => 'History Press',
                'publish_year' => 2021,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 199,
                'title' => 'Ensiklopedia Teknologi Geografi',
                'author' => 'Eratosthenes',
                'publisher' => 'Geography Press',
                'publish_year' => 2016,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
            [
                'id' => 200,
                'title' => 'Ensiklopedia Perpustakaan Digital',
                'author' => 'Michael Lesk',
                'publisher' => 'MIT Press',
                'publish_year' => 2017,
                'category_id' => 2,
                'stock' => 2,
                'location' => 'E5',
            ],
        ];

        $this->db->table('books')->insertBatch($data);
    }
}
